"""Add new columns to Vendor model

Revision ID: abc5cc7835f3
Revises: e389157bc8f9
Create Date: 2023-05-10 14:14:07.830596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc5cc7835f3'
down_revision = 'e389157bc8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('festival_number', sa.String(), server_default='49th', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_text', schema=None) as batch_op:
        batch_op.drop_column('festival_number')

    # ### end Alembic commands ###
