"""Add new columns to Vendor model

Revision ID: e389157bc8f9
Revises: 140e719cf77f
Create Date: 2023-05-09 22:49:38.642464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e389157bc8f9'
down_revision = '140e719cf77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_booth_price', sa.Float(), server_default='150', nullable=False))
        batch_op.add_column(sa.Column('twp_booths_price', sa.Float(), server_default='200', nullable=False))
        batch_op.add_column(sa.Column('one_booth_post_cutoff_price', sa.Float(), server_default='175', nullable=False))
        batch_op.add_column(sa.Column('two_booths_post_cutoff_price', sa.Float(), server_default='225', nullable=False))
        batch_op.add_column(sa.Column('deadline_date', sa.DateTime(timezone=True), server_default='2023-07-01T00:00:00', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('deadline_date')
        batch_op.drop_column('two_booths_post_cutoff_price')
        batch_op.drop_column('one_booth_post_cutoff_price')
        batch_op.drop_column('twp_booths_price')
        batch_op.drop_column('one_booth_price')

    # ### end Alembic commands ###
